name: Build and Validate

env:
  ProjectName : test

on:
  push:
    branches: ["development"]
    pull_request: ["development"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: print files
        run: dir

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore hackathon.acumatica.theta.sln

      - name: Build Solution
        run: msbuild.exe hackathon.acumatica.theta.sln /nologo /nr:false /p:Configuration=Release /target:Rebuild

      - name: Move dll
        run: Copy-Item "hackathon.acumatica.theta/bin/Release/netstandard2.0/hackathon.acumatica.theta.*" -Destination "_projects\hackathon.acumatica.theta\Bin"
     
      - name: print files
        run: dir
        
      - name: print files
        run: du .
        shell: bash
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: hackathon.acumatica.theta
          path: .\_projects\hackathon.acumatica.theta\

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: hackathon.acumatica.theta

    - name: Login
      run: |
        du .
        chmod +x ./.github/scripts/validate.sh
        ls | echo
        loginJson='{"name":"githubaction","password":"Theta","company":"Company","branch":""}'
        curl -X POST https://hackathon.acumatica.com/Theta/entity/auth/login -H "Content-Type: application/JSON" -d $loginJson -i --cookie-jar ./cookies.txt
    - name: Zips an Uploads
      run: |
        #sends file
        base64=$(base64 hackathon.acumatica.theta.zip)
        projectJson='{"projectLevel":1,"isReplaceIfExists":true,"projectName":"test","projectDescription":"Customization Project for Team Theta","projectContentBase64":"'"$base64"'"}'
        curl --location --request POST 'https://hackathon.acumatica.com/Theta/CustomizationApi/Import' --header 'Content-Type: application/json' -d "$projectJson" -i -b ./cookies.txt
    - name: Validate Project
      run:
        ./.github/scripts/validate.sh
